// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package job

import (
	"time"
)

const TableNameSysJobLog = "sys_job_log"

// SysJobLog mapped from table <sys_job_log>
type SysJobLog struct {
	JobLogID      int64      `gorm:"column:job_log_id;type:bigint;primaryKey;autoIncrement:true" json:"jobLogId"` // 任务日志ID
	JobName       string     `gorm:"column:job_name;type:varchar(64);not null" json:"jobName"`                    // 任务名称
	JobGroup      string     `gorm:"column:job_group;type:varchar(64);not null" json:"jobGroup"`                  // 任务组名
	InvokeTarget  string     `gorm:"column:invoke_target;type:varchar(500);not null" json:"invokeTarget"`         // 调用目标字符串
	JobMessage    *string    `gorm:"column:job_message;type:varchar(500)" json:"jobMessage"`                      // 日志信息
	Status        *string    `gorm:"column:status;type:char(1);default:0" json:"status"`                          // 执行状态（0正常 1失败）
	ExceptionInfo *string    `gorm:"column:exception_info;type:varchar(2000)" json:"exceptionInfo"`               // 异常信息
	CreateTime    *time.Time `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"createTime"`       // 创建时间
}

// TableName SysJobLog's table name
func (*SysJobLog) TableName() string {
	return TableNameSysJobLog
}
