// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package job

import (
	"time"
)

const TableNameSysJob = "sys_job"

// SysJob mapped from table <sys_job>
type SysJob struct {
	JobID          int64      `gorm:"column:job_id;type:bigint;primaryKey;autoIncrement:true" json:"jobId"`  // 任务ID
	JobName        string     `gorm:"column:job_name;type:varchar(64);primaryKey" json:"jobName"`            // 任务名称
	JobGroup       string     `gorm:"column:job_group;type:varchar(64);primaryKey" json:"jobGroup"`          // 任务组名
	InvokeTarget   string     `gorm:"column:invoke_target;type:varchar(500);not null" json:"invokeTarget"`   // 调用目标字符串
	CronExpression *string    `gorm:"column:cron_expression;type:varchar(255)" json:"cronExpression"`        // cron执行表达式
	MisfirePolicy  *string    `gorm:"column:misfire_policy;type:varchar(20);default:3" json:"misfirePolicy"` // 计划执行错误策略（1立即执行 2执行一次 3放弃执行）
	Concurrent     *string    `gorm:"column:concurrent;type:char(1);default:1" json:"concurrent"`            // 是否并发执行（0允许 1禁止）
	Status         *string    `gorm:"column:status;type:char(1);default:0" json:"status"`                    // 状态（0正常 1暂停）
	CreateBy       *string    `gorm:"column:create_by;type:varchar(64)" json:"createBy"`                     // 创建者
	CreateTime     *time.Time `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"createTime"` // 创建时间
	UpdateBy       *string    `gorm:"column:update_by;type:varchar(64)" json:"updateBy"`                     // 更新者
	UpdateTime     *time.Time `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"updateTime"` // 更新时间
	Remark         *string    `gorm:"column:remark;type:varchar(500)" json:"remark"`                         // 备注信息
}

// TableName SysJob's table name
func (*SysJob) TableName() string {
	return TableNameSysJob
}
