// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package system

import (
	"time"
)

const TableNameSysMenu = "sys_menu"

// SysMenu mapped from table <sys_menu>
type SysMenu struct {
	MenuID     int64      `gorm:"column:menu_id;type:bigint;primaryKey;autoIncrement:true" json:"menuId"` // 菜单ID
	MenuName   string     `gorm:"column:menu_name;type:varchar(50);not null" json:"menuName"`             // 菜单名称
	ParentID   int64      `gorm:"column:parent_id;type:bigint" json:"parentId"`                           // 父菜单ID
	OrderNum   int64      `gorm:"column:order_num;type:int" json:"orderNum"`                              // 显示顺序
	Path       string     `gorm:"column:path;type:varchar(200)" json:"path"`                              // 路由地址
	Component  string     `gorm:"column:component;type:varchar(255)" json:"component"`                    // 组件路径
	Query      string     `gorm:"column:query;type:varchar(255)" json:"query"`                            // 路由参数
	IsFrame    int64      `gorm:"column:is_frame;type:int;default:1" json:"isFrame"`                      // 是否为外链（0是 1否）
	IsCache    int64      `gorm:"column:is_cache;type:int" json:"isCache"`                                // 是否缓存（0缓存 1不缓存）
	MenuType   string     `gorm:"column:menu_type;type:char(1)" json:"menuType"`                          // 菜单类型（M目录 C菜单 F按钮）
	Visible    string     `gorm:"column:visible;type:char(1);default:0" json:"visible"`                   // 菜单状态（0显示 1隐藏）
	Status     string     `gorm:"column:status;type:char(1);default:0" json:"status"`                     // 菜单状态（0正常 1停用）
	Perms      string     `gorm:"column:perms;type:varchar(100)" json:"perms"`                            // 权限标识
	Icon       string     `gorm:"column:icon;type:varchar(100);default:#" json:"icon"`                    // 菜单图标
	CreateBy   string     `gorm:"column:create_by;type:varchar(64)" json:"createBy"`                      // 创建者
	CreateTime time.Time  `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"createTime"`  // 创建时间
	UpdateBy   string     `gorm:"column:update_by;type:varchar(64)" json:"updateBy"`                      // 更新者
	UpdateTime time.Time  `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"updateTime"`  // 更新时间
	Remark     string     `gorm:"column:remark;type:varchar(500)" json:"remark"`                          // 备注
	Children   []*SysMenu `gorm:"-" json:"children"`                                                      // 子菜单
	ArrIdx     int        `gorm:"-" json:"arrIdx"`                                                        // 临时变量 用于生成tree
}

// TableName SysMenu's table name
func (*SysMenu) TableName() string {
	return TableNameSysMenu
}
