// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package system

import (
	"time"
)

const TableNameSysDictDatum = "sys_dict_data"

// SysDictData mapped from table <sys_dict_data>
type SysDictData struct {
	DictCode   int64     `gorm:"column:dict_code;type:bigint;primaryKey;autoIncrement:true" json:"dictCode"` // 字典编码
	DictSort   int64     `gorm:"column:dict_sort;type:int" json:"dictSort"`                                  // 字典排序
	DictLabel  string    `gorm:"column:dict_label;type:varchar(100)" json:"dictLabel"`                       // 字典标签
	DictValue  string    `gorm:"column:dict_value;type:varchar(100)" json:"dictValue"`                       // 字典键值
	DictType   string    `gorm:"column:dict_type;type:varchar(100)" json:"dictType"`                         // 字典类型
	CSSClass   string    `gorm:"column:css_class;type:varchar(100)" json:"cssClass"`                         // 样式属性（其他样式扩展）
	ListClass  string    `gorm:"column:list_class;type:varchar(100)" json:"listClass"`                       // 表格回显样式
	IsDefault  string    `gorm:"column:is_default;type:char(1);default:N" json:"isDefault"`                  // 是否默认（Y是 N否）
	Status     string    `gorm:"column:status;type:char(1);default:0" json:"status"`                         // 状态（0正常 1停用）
	CreateBy   string    `gorm:"column:create_by;type:varchar(64)" json:"createBy"`                          // 创建者
	CreateTime time.Time `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"createTime"`      // 创建时间
	UpdateBy   string    `gorm:"column:update_by;type:varchar(64)" json:"updateBy"`                          // 更新者
	UpdateTime time.Time `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"updateTime"`      // 更新时间
	Remark     string    `gorm:"column:remark;type:varchar(500)" json:"remark"`                              // 备注
}

// TableName SysDictDatum's table name
func (*SysDictData) TableName() string {
	return TableNameSysDictDatum
}
