// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package system

import (
	"time"
)

const TableNameSysConfig = "sys_config"

// SysConfig mapped from table <sys_config>
type SysConfig struct {
	ConfigID    int64     `gorm:"column:config_id;type:int;primaryKey;autoIncrement:true" json:"configId"` // 参数主键
	ConfigName  string    `gorm:"column:config_name;type:varchar(100)" json:"configName"`                  // 参数名称
	ConfigKey   string    `gorm:"column:config_key;type:varchar(100)" json:"configKey"`                    // 参数键名
	ConfigValue string    `gorm:"column:config_value;type:varchar(500)" json:"configValue"`                // 参数键值
	ConfigType  string    `gorm:"column:config_type;type:char(1);default:N" json:"configType"`             // 系统内置（Y是 N否）
	CreateBy    string    `gorm:"column:create_by;type:varchar(64)" json:"createBy"`                       // 创建者
	CreateTime  time.Time `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"createTime"`   // 创建时间
	UpdateBy    string    `gorm:"column:update_by;type:varchar(64)" json:"updateBy"`                       // 更新者
	UpdateTime  time.Time `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"updateTime"`   // 更新时间
	Remark      string    `gorm:"column:remark;type:varchar(500)" json:"remark"`                           // 备注
}

// TableName SysConfig's table name
func (*SysConfig) TableName() string {
	return TableNameSysConfig
}
