// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package system

const TableNameSysRoleMenu = "sys_role_menu"

// SysRoleMenu mapped from table <sys_role_menu>
type SysRoleMenu struct {
	RoleID int64 `gorm:"column:role_id;type:bigint;primaryKey" json:"roleId"` // 角色ID
	MenuID int64 `gorm:"column:menu_id;type:bigint;primaryKey" json:"menuId"` // 菜单ID
}

// TableName SysRoleMenu's table name
func (*SysRoleMenu) TableName() string {
	return TableNameSysRoleMenu
}
