// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package system

import (
	"time"
)

const TableNameSysUser = "sys_user"

// SysUser mapped from table <sys_user>
type SysUser struct {
	UserID      int64      `gorm:"column:user_id;type:bigint;primaryKey;autoIncrement:true" json:"userId"` // 用户ID
	DeptID      int64      `gorm:"column:dept_id;type:bigint" json:"deptId"`                               // 部门ID
	Username    string     `gorm:"column:username;type:varchar(30);not null" json:"username"`              // 用户账号
	Nickname    string     `gorm:"column:nickname;type:varchar(30);not null" json:"nickname"`              // 用户昵称
	UserType    string     `gorm:"column:user_type;type:varchar(2);default:00" json:"userType"`            // 用户类型（00系统用户）
	Email       string     `gorm:"column:email;type:varchar(50)" json:"email"`                             // 用户邮箱
	PhoneNumber string     `gorm:"column:phone_number;type:varchar(11)" json:"phoneNumber"`                // 手机号码
	Gender      string     `gorm:"column:gender;type:char(1);default:0" json:"gender"`                     // 用户性别（0男 1女 2未知）
	Avatar      string     `gorm:"column:avatar;type:varchar(100)" json:"avatar"`                          // 头像地址
	Password    string     `gorm:"column:password;type:varchar(100)" json:"password"`                      // 密码
	Status      string     `gorm:"column:status;type:char(1);default:0" json:"status"`                     // 帐号状态（0正常 1停用）
	DelFlag     string     `gorm:"column:del_flag;type:char(1);default:0" json:"delFlag"`                  // 删除标志（0代表存在 2代表删除）
	LoginIP     string     `gorm:"column:login_ip;type:varchar(128)" json:"loginIp"`                       // 最后登录IP
	LoginDate   *time.Time `gorm:"column:login_date;type:datetime" json:"loginDate"`                       // 最后登录时间
	CreateBy    string     `gorm:"column:create_by;type:varchar(64)" json:"createBy"`                      // 创建者
	CreateTime  time.Time  `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"createTime"`  // 创建时间
	UpdateBy    string     `gorm:"column:update_by;type:varchar(64)" json:"updateBy"`                      // 更新者
	UpdateTime  *time.Time `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"updateTime"`  // 更新时间
	Remark      string     `gorm:"column:remark;type:varchar(500)" json:"remark"`                          // 备注
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}

func (*SysUser) IsAdmin(userId int64) bool {
	return userId == 1
}
