// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package system

import (
	"time"
)

const TableNameSysDept = "sys_dept"

// SysDept mapped from table <sys_dept>
type SysDept struct {
	DeptID     int64      `gorm:"column:dept_id;type:bigint;primaryKey;autoIncrement:true" json:"deptId"` // 部门id
	ParentID   int64      `gorm:"column:parent_id;type:bigint" json:"parentId"`                           // 父部门id
	Ancestors  string     `gorm:"column:ancestors;type:varchar(50)" json:"ancestors"`                     // 祖级列表
	DeptName   string     `gorm:"column:dept_name;type:varchar(30)" json:"deptName"`                      // 部门名称
	OrderNum   int64      `gorm:"column:order_num;type:int" json:"orderNum"`                              // 显示顺序
	Leader     string     `gorm:"column:leader;type:varchar(20)" json:"leader"`                           // 负责人
	Phone      string     `gorm:"column:phone;type:varchar(11)" json:"phone"`                             // 联系电话
	Email      string     `gorm:"column:email;type:varchar(50)" json:"email"`                             // 邮箱
	Status     string     `gorm:"column:status;type:char(1);default:0" json:"status"`                     // 部门状态（0正常 1停用）
	DelFlag    string     `gorm:"column:del_flag;type:char(1);default:0" json:"delFlag"`                  // 删除标志（0代表存在 2代表删除）
	CreateBy   string     `gorm:"column:create_by;type:varchar(64)" json:"createBy"`                      // 创建者
	CreateTime time.Time  `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"createTime"`  // 创建时间
	UpdateBy   string     `gorm:"column:update_by;type:varchar(64)" json:"updateBy"`                      // 更新者
	UpdateTime time.Time  `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"updateTime"`  // 更新时间
	Children   []*SysDept `gorm:"-" json:"children"`                                                      // 子部门
	ArrIdx     int        `gorm:"-" json:"arrIdx"`                                                        // 临时变量 用于生成tree
}

// TableName SysDept's table name
func (*SysDept) TableName() string {
	return TableNameSysDept
}
