// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package system

import (
	"time"
)

const TableNameSysDictType = "sys_dict_type"

// SysDictType mapped from table <sys_dict_type>
type SysDictType struct {
	DictID     int64     `gorm:"column:dict_id;type:bigint;primaryKey;autoIncrement:true" json:"dictId"` // 字典主键
	DictName   string    `gorm:"column:dict_name;type:varchar(100)" json:"dictName"`                     // 字典名称
	DictType   string    `gorm:"column:dict_type;type:varchar(100)" json:"dictType"`                     // 字典类型
	Status     string    `gorm:"column:status;type:char(1);default:0" json:"status"`                     // 状态（0正常 1停用）
	CreateBy   string    `gorm:"column:create_by;type:varchar(64)" json:"createBy"`                      // 创建者
	CreateTime time.Time `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"createTime"`  // 创建时间
	UpdateBy   string    `gorm:"column:update_by;type:varchar(64)" json:"updateBy"`                      // 更新者
	UpdateTime time.Time `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"updateTime"`  // 更新时间
	Remark     string    `gorm:"column:remark;type:varchar(500)" json:"remark"`                          // 备注
}

// TableName SysDictType's table name
func (*SysDictType) TableName() string {
	return TableNameSysDictType
}
