// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package monitor

import (
	"time"
)

const TableNameSysOperLog = "sys_oper_log"

// SysOperLog mapped from table <sys_oper_log>
type SysOperLog struct {
	OperID        int64      `gorm:"column:oper_id;type:bigint;primaryKey;autoIncrement:true" json:"operId"` // 日志主键
	Title         *string    `gorm:"column:title;type:varchar(50)" json:"title"`                             // 模块标题
	BusinessType  *int64     `gorm:"column:business_type;type:int" json:"businessType"`                      // 业务类型（0其它 1新增 2修改 3删除）
	Method        *string    `gorm:"column:method;type:varchar(100)" json:"method"`                          // 方法名称
	RequestMethod *string    `gorm:"column:request_method;type:varchar(10)" json:"requestMethod"`            // 请求方式
	OperatorType  *int64     `gorm:"column:operator_type;type:int" json:"operatorType"`                      // 操作类别（0其它 1后台用户 2手机端用户）
	OperName      *string    `gorm:"column:oper_name;type:varchar(50)" json:"operName"`                      // 操作人员
	DeptName      *string    `gorm:"column:dept_name;type:varchar(50)" json:"deptName"`                      // 部门名称
	OperURL       *string    `gorm:"column:oper_url;type:varchar(255)" json:"operUrl"`                       // 请求URL
	OperIP        *string    `gorm:"column:oper_ip;type:varchar(128)" json:"operIp"`                         // 主机地址
	OperLocation  *string    `gorm:"column:oper_location;type:varchar(255)" json:"operLocation"`             // 操作地点
	OperParam     *string    `gorm:"column:oper_param;type:varchar(2000)" json:"operParam"`                  // 请求参数
	JSONResult    *string    `gorm:"column:json_result;type:varchar(2000)" json:"jsonResult"`                // 返回参数
	Status        *int64     `gorm:"column:status;type:int" json:"status"`                                   // 操作状态（0正常 1异常）
	ErrorMsg      *string    `gorm:"column:error_msg;type:varchar(2000)" json:"errorMsg"`                    // 错误消息
	OperTime      *time.Time `gorm:"column:oper_time;type:datetime" json:"operTime"`                         // 操作时间
}

// TableName SysOperLog's table name
func (*SysOperLog) TableName() string {
	return TableNameSysOperLog
}
